#Use the official python image from the docker hub
FROM python:3.9-slim

#Set the working directory
WORKDIR /app

#Copy the current directory contents into the container at /app
COPY . /app

#Install any needed packages specified in the requirements.txt
RUN pip install flask

# Make port 5000 available to the world outside the container
EXPOSE 5000

# Run app.py
CMD ['Python','app.py']